/** Declaration file generated by dts-gen */

export = logdown;

declare class logdown {
    constructor(prefix: any, opts: any);

    debug(...args: any[]): void;

    error(...args: any[]): void;

    info(...args: any[]): void;

    log(...args: any[]): void;

    warn(...args: any[]): void;

    static disable(...args: any[]): void;

    static enable(...args: any[]): void;

}

declare namespace logdown {
    namespace disable {
        const prototype: {
        };

    }

    namespace enable {
        const prototype: {
        };

    }

    namespace prototype {
        function debug(...args: any[]): void;

        function error(...args: any[]): void;

        function info(...args: any[]): void;

        function log(...args: any[]): void;

        function warn(...args: any[]): void;

        namespace debug {
            const prototype: {
            };

        }

        namespace error {
            const prototype: {
            };

        }

        namespace info {
            const prototype: {
            };

        }

        namespace log {
            const prototype: {
            };

        }

        namespace warn {
            const prototype: {
            };

        }

    }

}
